<a href="https://colab.research.google.com/github/a-forty-two/DataSetsForML/blob/master/08_IntroToTF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# CREATE A DIRECTED ACYCLIC GRAPH 
# ONCE THIS GRAPH IS CREATED, it needs to run in a session 
# this 1 run is called an epoch 
# this 1 run is divided into many steps 

import tensorflow as tf
# color classification problem
# generate some random RGB color values, and their classes 
inputs = [[200,0,1],[215,70,4],[0,0,200],[5,0,230]]
ouputs = [[1],[1],[0],[0]]
# TENSORFLOW ONLY ACCEPTS TENSORS 
# LISTSET => VALUES ONE AFTER THE OTHER, lists can even contain more lists
# each list depth is a new dimension
trainingInputs = tf.convert_to_tensor(value=inputs, dtype=tf.int8) # nos upto 1 byte long



In [3]:
session = tf.Session()
print(session.run(fetches=trainingInputs))
session.close()

[[-56  98  17]
 [ 15  70 114]]


In [0]:
#import tensorflow as tf
# color classification problem
# generate some random RGB color values, and their classes 
#inputs = [[200,0,1],[215,70,4],[0,0,200],[5,0,230]]
#ouputs = [[1],[1],[0],[0]]
# TENSORFLOW ONLY ACCEPTS TENSORS 
# LISTSET => VALUES ONE AFTER THE OTHER, lists can even contain more lists
# each list depth is a new dimension






#trainingInputs = tf.convert_to_tensor(value=inputs, dtype=tf.int8) # nos upto 1 byte long
#session = tf.Session()
#session.run(tf.global_variables_initializer())
#for step in range(100):
  #


#print(session.run(fetches=trainingInputs))
#session.close()

In [0]:
import tensorflow as tf
# let's discuss only a single layer
# 3-d input, 1-d output
# 3 weights, 1 bias
traininginputs = tf.placeholder(shape=[None,3], dtype=tf.float32)
trainingoutputs = tf.placeholder(shape=[None,1], dtype=tf.float32)
weights = tf.Variable(initial_value=[[0.3],[0.1],[0.7]], dtype=tf.float32)
bias = tf.Variable(initial_value=[[1]], dtype=tf.float32)


# PLACEHOLDER ->During execution, this value is used again and again
# VARIABLES -> During execution, this value changes frequently/per step
# weights, biases -> tf.variable
# ip/op -> tf.placeholder 

In [6]:
# SINGLE LAYER MODEL
# y = f(x) = mx + c
y = tf.matmul(traininginputs, weights) + bias
predictions = tf.nn.sigmoid(y)
prediction_error = tf.reduce_sum(trainingoutputs - predictions)
train_op = tf.train.GradientDescentOptimizer(learning_rate=0.05).minimize(prediction_error)
# LEARNING RATE SHOULD BE A HYPERPARAMETER
prediction_error # THIS IS JUST A FUNCTION/NODE/TRANSFORMATION on the Directed Acyclic Graph
# it is NOT a real value
# ONLY EXECUTED ON RUN TIME! no compile time execution possible
# weights and biases are calculated only on RUNTIME 

# what if you wanted a hard-coded, non-dynamic, non-static, quick calculation, use TF.EAGER
# it does an EAGER evaluation instead of LAZY evaluation 
# it does not wait for a DAG to be created, it forms a direct equation

<tf.Tensor 'Sum_1:0' shape=() dtype=float32>

In [11]:
session = tf.Session()
# when using placeholder and variables, initialize them in beginning of run
session.run(tf.global_variables_initializer())
inputs = [[200,0,1],[215,70,4],[0,0,200],[5,0,230]]
outputs = [[1],[1],[0],[0]]
for step in range(1000):
  session.run(fetches=[train_op], feed_dict={traininginputs:inputs, trainingoutputs:outputs})
print(session.run(weights))
print(session.run(bias))
print(session.run(fetches=predictions, feed_dict={traininginputs:[[254,0,0],[0,0,230]]}))
session.close()
# NO NEW LEARNING 


[[0.3]
 [0.1]
 [0.7]]
[[1.]]
[[1.]
 [1.]]


In [7]:
def abc():
  return 'hello'

abc

<function __main__.abc>